---
title: "Analyze Points"
output: html_notebook
---

```{r}
library(tidyverse)
library(mapdata)
```

```{r}
filename <- "~/Dropbox/data/usps/post_offices.pipe.csv"
data <- read_delim(filename, "|", col_names = FALSE)
```

```{r}
colnames(data) <- c('type', 'id', 'lat', 'lon', 'name')
```

```{r}
usa <- map_data("usa")
```


```{r}

data %>%
  ggplot() + 
  geom_polygon(data = usa, aes(x = long, y = lat, group = group)) + 
  geom_point(data = data, aes(x = lon, y = lat), r = 3, color = 'red', alpha = 1 / 10) +
  coord_quickmap()
```

```{r}
write_csv(data, "~/code/js/geo-explore/data/post_offices.csv")
```


```{r}
library(sp)
library(maps)
library(maptools)
library(tidyverse)
```

```{r}
# optionally read from the data CSV
data <- read_csv('../data/post_offices.csv') 
```

```{r}
lonlat <- data %>%
  select(lon, lat)
latlong2state <- function(pointsDF) {
    # Prepare SpatialPolygons object with one SpatialPolygon
    # per state (plus DC, minus HI & AK)
    states <- maps::map('state', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Convert pointsDF to a SpatialPoints object 
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Use 'over' to get _indices_ of the Polygons object containing each point 
    indices <- over(pointsSP, states_sp)

    # Return the state names of the Polygons object containing each point
    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stateNames[indices]
}

```

```{r}
states <- latlong2state(lonlat)
stateFips <- as_tibble(state.fips) %>% 
  select(polyname, abb, fips) %>%
  rename(state = polyname, stateAbbr = abb, stateFips = fips) %>%
  mutate(stateFips = str_pad(stateFips, 2, pad =))

dataWithStates <- data %>% 
  mutate(state = states) %>%
  filter(!is.na(state)) %>% 
  left_join(stateFips)

dataWithStates
```

```{r}
write_csv(dataWithStates, "../data/post_offices_with_states.csv")
```

